### ISSUE TITLE
Could not successfully deploy 

### ISSUE THREAD

**Issue by PankajJaswalDrish** [IBM/node-red-app#33]
We followed the same steps as described in Github Readme file.

We successfully deploy the github code to IBM cloud but the node-red app is stopped. I tried to run but it process the first stage and when it came to the second stage it failed again and again. 

An error message is pop on my screen:

 ****"Error : An error occurred performing the operation. Try again later.
Description:
You have exceeded your organization's memory limit: app requested more memory than available (CF-AppMemoryQuotaExceeded - 100005)"****

Please guide or help me out from this problem.

Thanks & Regards
Pankaj Jaswal

**Comment by knolleary** [comment]
Hi @PankajJaswalDrish 

the default behaviour of the pipeline is to start a second copy of the application, verify its deployed successfully and then switch the routes over from the old instance to the new instance and delete the old instance.

This means, for a short period of time, there will be two copies of the app running.

You are hitting this error because your account does not have the spare memory available to run the second copy.

The workaround is to manually stop your Node-RED application first (stopped apps don't count towards your memory usage) - you will then be able to run the deploy.
